# Generated by Django 3.1.2 on 2020-10-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TheCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.TextField()),
                ('model', models.TextField()),
                ('rate1', models.IntegerField(default=0)),
                ('rate2', models.IntegerField(default=0)),
                ('rate3', models.IntegerField(default=0)),
                ('rate4', models.IntegerField(default=0)),
                ('rate5', models.IntegerField(default=0)),
                ('rates', models.IntegerField(default=0)),
            ],
        ),
    ]
